export const FETCH_TVSHOWS_REQUEST = "FETCH_TVSHOWS_REQUEST";
export const FETCH_TVSHOWS_SUCCESS = "FETCH_TVSHOWS_SUCCESS";
export const FETCH_TVSHOWS_FAILURE = "FETCH_TVSHOWS_FAILURE";
export const RESET_TVSHOWS_LIST = "RESET_TVSHOWS_LIST";
export const FETCH_TVSHOW_DETAILS_REQUEST = "FETCH_TVSHOW_DETAILS_REQUEST";
export const FETCH_TVSHOW_DETAILS_SUCCESS = "FETCH_TVSHOW_DETAILS_SUCCESS";
export const FETCH_TVSHOW_DETAILS_FAILURE = "FETCH_TVSHOW_DETAILS_FAILURE";
export const RESET_TVSHOW_DETAILS = "RESET_TVSHOW_DETAILS";